architect:
  - Glusk2
docker:
  image: "mingc/android-build-box:1.12.0"
  as_root: true
release:
  script:
    - "chmod +x gradlew"
    # Increment versionCode
    - "perl -i.orig -pe '/versionCode/ && s/([0-9]+)/$1+1 . $2/e' android/build.gradle"
    # Update project version to $tag
    - ./gradlew updateVersion -Prelease.useAutomaticVersion=true -PnewVersion=$tag
    # Build the project
    - ./gradlew build connectedCheck
    # Commit new version and versionCode
    - git commit -am "Release $tag"
    - git push origin master
