architect:
  - Glusk2
docker:
  image: "mingc/android-build-box:1.12.0"
release:
  script:
    - "chmod +x gradlew"
    # Increment versionCode
    - "perl -i.orig -pe '/versionCode/ && s/([0-9]+)/$1+1 . $2/e' android/build.gradle"
    # Bump project version
    - "./gradlew release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=$tag -Prelease.newVersion=$tag-SNAPSHOT"
