language: android # can be 'java' if there is no android build target
android:
  components:
    - build-tools-28.0.3
    - android-28
    - doc
jdk: oraclejdk8
dist: trusty

# Cache gradle dependencies (should be faster to download them from cache)
cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/caches/modules-2/files-2.1

# Setup environment
before_install:
  - chmod +x gradlew

# Default gradle task will be run automatically on build, no need to define it

# Deployment to GitHub-releases
before_deploy:
  # Generate a packaged jar for the desktop-project and rename it to include the tag
  - ./gradlew desktop:dist
  - mv desktop/build/libs/desktop-*.jar desktop/build/libs/sprouts-$TRAVIS_TAG.jar
  # Generate a packaged apk for the android-project and rename it (this apk is unsigned/unaligned)
  - ./gradlew android:assembleRelease
  - mv android/build/outputs/apk/release/android-release-unsigned.apk android/build/outputs/apk/release/sprouts-$TRAVIS_TAG-unaligned.apk
  # Generate and zip deployment files for the HTML project
  - ./gradlew html:dist
  - zip -r sprouts-$TRAVIS_TAG.zip ./html/build/dist/
deploy:
  - provider: releases
    api_key:
      secure: $DEPLOYMENT_KEY
    file:
      # Define which files should be deployed to GitHub
      - desktop/build/libs/sprouts-$TRAVIS_TAG.jar
      - android/build/outputs/apk/release/sprouts-$TRAVIS_TAG-unaligned.apk
      - sprouts-$TRAVIS_TAG.zip
    on:
      tags: true
      repo: Glusk2/sprouts
      branch: master
      condition: $TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+.*$ # Only deploy tags that match something like v1.0.0
  - provider: script
    api_key:
      secure: $BUTLER_API_KEY
    script: bash deploy.sh
    on:
      tags: true
      repo: Glusk2/sprouts
      branch: master
      condition: $TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+.*$ # Only deploy tags that match something like v1.0.0
