# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: GitHub Pull Request Build

on:
  pull_request:
    branches: [ master ]
  push:
    branches-ignore:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Android SDK
      uses: malinskiy/action-android/install-sdk@release/0.1.1
    - name: Install Android packages
      run: sdkmanager "platforms;android-28" "platform-tools" "build-tools;28.0.3"
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build connectedCheck
    - name: Generate coverage
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: ./gradlew core:jacocoTestReport core:coveralls
