name: GitHub Tagged Release

# Controls when the action will run. 
on:
  push:
    tags:
      - '^v[0-9]+.[0-9]+.[0-9]+.*$'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get release TAG
      run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Android SDK
      uses: malinskiy/action-android/install-sdk@release/0.1.1
    - name: Install Android packages
      run: sdkmanager "platforms;android-28" "platform-tools" "build-tools;28.0.3"
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate Android release APK
      run: ./gradlew android:assembleRelease
    - name: Sign Android release APK
      uses: r0adkll/sign-android-release@v1
      # ID used to access action output
      id: sign_app
      with:
        releaseDirectory: android/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        # override default build-tools version (29.0.3) -- optional
        BUILD_TOOLS_VERSION: "28.0.3"
      # Example use of `signedReleaseFile` output -- not needed
    - name: Tag Android release APK
      run: mv ${{steps.sign_app.outputs.signedReleaseFile}} android/build/outputs/apk/release/sprouts-$TAG.apk
    - name: Generate desktop release
      run: |
        ./gradlew desktop:dist
        mv desktop/build/libs/desktop-*.jar desktop/build/libs/sprouts-$TAG.jar
    - name: Generate HTML release
      run: |
        ./gradlew html:dist
        zip -r sprouts-$TRAVIS_TAG.zip ./html/build/dist/
    - name: Butler deploy
      run: ./deploy.sh
